-- Seed 5 authors with books and blog posts
-- Uses INSERT OR IGNORE to avoid conflicts

-- Fix Dr. Kibet Kitur status so his content displays publicly
UPDATE Author SET status = 'APPROVED', approvedAt = COALESCE(approvedAt, datetime('now')) WHERE id = 'author-user-kibet-kitur';

-- Authors (4 existing seed users + 1 new author user)
INSERT OR IGNORE INTO Author (id, userId, bio, profileImage, status, isActive, createdAt, updatedAt) VALUES
('author-user-john-kamau', 'user-john-kamau', 'Collector and preserver of traditional Kalenjin folklore tales passed down through generations.', 'https://ui-avatars.com/api/?name=John+Kamau&size=200&background=4A90E2&color=fff&bold=true', 'APPROVED', 1, datetime('now'), datetime('now')),
('author-user-jane-kiplagat', 'user-jane-kiplagat', 'Scholar of Kalenjin traditions and cultural practices, translating ancient wisdom for modern readers.', 'https://ui-avatars.com/api/?name=Jane+Kiplagat&size=200&background=50C878&color=fff&bold=true', 'APPROVED', 1, datetime('now'), datetime('now')),
('author-user-mike-korir', 'user-mike-korir', 'Historian documenting the rich cultural heritage of the Kalenjin people.', 'https://ui-avatars.com/api/?name=Mike+Korir&size=200&background=9B59B6&color=fff&bold=true', 'APPROVED', 1, datetime('now'), datetime('now')),
('author-user-sarah-chebet', 'user-sarah-chebet', 'Children''s book author and storyteller preserving Kalenjin culture through words.', 'https://ui-avatars.com/api/?name=Sarah+Chebet&size=200&background=E07856&color=fff&bold=true', 'APPROVED', 1, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO User (id, email, password, name, role, createdAt, updatedAt) VALUES
('user-peter-kiplangat', 'peter.kiplangat@kaleereads.com', '$2a$10$rOJ7FqZxQj3GxM5vYZxZ4.xKqF5xQxQxQxQxQxQxQxQxQxQxQxQxQ', 'Peter Kiplangat', 'AUTHOR', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO Author (id, userId, bio, profileImage, status, isActive, createdAt, updatedAt) VALUES
('author-user-peter-kiplangat', 'user-peter-kiplangat', 'Poet and oral historian weaving Kalenjin proverbs, songs and chants into contemporary verse.', 'https://ui-avatars.com/api/?name=Peter+Kiplangat&size=200&background=D4AF37&color=fff&bold=true', 'APPROVED', 1, datetime('now'), datetime('now'));

-- Books
INSERT OR IGNORE INTO Book (id, title, description, coverImage, fileKey, fileSize, fileType, price, previewPages, category, language, isPublished, publishedAt, authorId, createdAt, updatedAt) VALUES
('book-2', 'Kalenjin Folklore Tales', 'A captivating collection of traditional Kalenjin stories passed down through generations. These tales feature the wisdom of elders, the cunning of animals, and the beauty of the Rift Valley landscape. Each story carries deep cultural significance and moral lessons that have shaped the Kalenjin community for centuries.', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=900&fit=crop', 'books/book-2/folklore-tales.pdf', 3145728, 'pdf', 500, 15, 'Folklore', 'Kalenjin', 1, '2022-06-20', 'author-user-john-kamau', datetime('now'), datetime('now')),
('book-3', 'Traditional Wisdom of the Kalenjin', 'An exploration of the philosophical and practical wisdom embedded in Kalenjin traditions. From agricultural practices to social customs, this book reveals the deep knowledge systems of the community.', 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&h=900&fit=crop', 'books/book-3/traditional-wisdom.pdf', 4194304, 'pdf', 750, 18, 'Non-Fiction', 'Bilingual', 1, '2023-03-10', 'author-user-jane-kiplagat', datetime('now'), datetime('now')),
('book-4', 'Cultural Heritage of the Kalenjin', 'A comprehensive look at the rich cultural heritage of the Kalenjin people, documenting ceremonies, rituals, and the evolution of traditions over time.', 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&h=900&fit=crop', 'books/book-4/cultural-heritage.pdf', 4718592, 'pdf', 600, 12, 'History', 'English', 1, '2021-09-05', 'author-user-mike-korir', datetime('now'), datetime('now')),
('book-5', 'Children Stories from the Rift Valley', 'Immerse your child in the magical world of African storytelling with this delightful collection of fables and adventures. Featuring beloved characters like the clever hare, the mighty lion, and the wise tortoise. Each story entertains while imparting valuable life lessons about friendship, courage, and honesty.', 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&h=900&fit=crop', 'books/book-5/children-stories.pdf', 2097152, 'pdf', 400, 10, 'Children', 'English & Kalenjin', 1, '2023-11-12', 'author-user-sarah-chebet', datetime('now'), datetime('now')),
('book-6', 'The Chants of the Highlands', 'A lyrical journey through the songs, chants and proverbs of the Kalenjin people, collected from elders across the highlands and rendered in poetic form for the modern reader.', 'https://images.unsplash.com/photo-1474932430478-367dbb0152b1?w=600&h=900&fit=crop', 'books/book-6/chants-of-the-highlands.pdf', 3670016, 'pdf', 850, 16, 'Poetry', 'Bilingual', 1, '2024-05-01', 'author-user-peter-kiplangat', datetime('now'), datetime('now'));

-- Blog Posts
INSERT OR IGNORE INTO BlogPost (id, title, slug, content, excerpt, coverImage, coverType, category, isPublished, publishedAt, viewCount, authorId, createdAt, updatedAt) VALUES
('blog-1', 'The Rich History of Kalenjin Literature', 'rich-history-kalenjin-literature', '<h2>Introduction to Kalenjin Literary Tradition</h2><p>The Kalenjin people have a rich oral and written literary tradition that spans generations. From the fireside tales of grandmothers to the ceremonial chants of elders, stories have always been the heartbeat of our community.</p><p>In this post we explore how these oral traditions evolved into the written works you see today, and why preserving them matters for generations to come.</p>', 'Exploring the evolution of Kalenjin literature from oral traditions to modern written works.', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=600&fit=crop', 'image', 'Culture', 1, '2024-11-15', 245, 'author-user-sarah-chebet', datetime('now'), datetime('now')),
('blog-2', 'How to Write Compelling Folklore Stories', 'how-to-write-compelling-folklore-stories', '<h2>Mastering the Art of Folklore Writing</h2><p>Writing folklore requires a delicate balance between preserving tradition and engaging modern readers.</p><p>Start with a story your grandmother told you, keep the lesson at the centre, and let the setting come alive through sensory detail.</p>', 'A comprehensive guide for aspiring writers on how to craft authentic and engaging folklore stories.', 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop', 'image', 'Guides', 1, '2024-11-20', 189, 'author-user-sarah-chebet', datetime('now'), datetime('now')),
('blog-3', 'The Clever Hare and the Lion: A Kalenjin Fable', 'clever-hare-and-the-lion-kalenjin-fable', '<h2>The Clever Hare Outwits the Lion</h2><p>In the days when the Rift Valley was young, the lion claimed ownership of every watering hole. But the clever hare, small and quick, knew that wisdom is mightier than strength.</p><p>This beloved fable reminds us that brains always overcome brawn, a lesson passed from one generation to the next.</p>', 'The classic Kalenjin fable of wit triumphing over strength, retold for a new generation.', 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=800&h=600&fit=crop', 'image', 'Stories', 1, '2024-12-02', 312, 'author-user-john-kamau', datetime('now'), datetime('now')),
('blog-4', 'Why We Preserve Our Ancestral Chants', 'why-we-preserve-ancestral-chants', '<h2>The Power of the Spoken Word</h2><p>Every chant carries a memory. Every song holds a history. The Kalenjin people have always sung their stories, from beer-drinking songs to war chants of old.</p><p>Collecting these chants is more than nostalgia; it is a duty. Read about how poetry keeps our identity alive.</p>', 'A poet reflects on why Kalenjin chants and songs must be preserved for future generations.', 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop', 'image', 'Culture', 1, '2025-01-08', 156, 'author-user-peter-kiplangat', datetime('now'), datetime('now')),
('blog-5', 'Traditional Ceremonies Through the Seasons', 'traditional-ceremonies-through-the-seasons', '<h2>Rituals That Mark Our Calendar</h2><p>From initiation ceremonies to harvest blessings, the Kalenjin calendar is a tapestry of traditions.</p><p>Join us as we document these ceremonies before they fade, and understand the wisdom each one carries for the community and for the individual.</p>', 'A scholar documents the ceremonies and rituals that define the Kalenjin year.', 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=800&h=600&fit=crop', 'image', 'Culture', 1, '2025-01-20', 128, 'author-user-jane-kiplagat', datetime('now'), datetime('now')),
('blog-6', 'Teaching Children the Stories of the Elders', 'teaching-children-stories-of-elders', '<h2>Storytime as a Cultural Anchor</h2><p>Reading to children is how culture survives. The fables we share today become the identity our children carry tomorrow.</p><p>Here are five Kalenjin tales perfect for bedtime, each with the moral lesson that has guided our community for centuries.</p>', 'Practical tips and five beloved Kalenjin tales to share with the young ones.', 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=600&fit=crop', 'image', 'Stories', 1, '2025-02-10', 203, 'author-user-mike-korir', datetime('now'), datetime('now')),
('blog-7', 'Kalenjin Proverbs: Wisdom in a Few Words', 'kalenjin-proverbs-wisdom-in-a-few-words', '<h2>The Proverbs That Guide Us</h2><p>A proverb is a whole philosophy in a single sentence. The Kalenjin people have one for almost every situation in life.</p><p>In this collection we share twenty-five proverbs with their meanings, showing how our ancestors packed generations of wisdom into short, memorable sayings.</p>', 'Twenty-five timeless Kalenjin proverbs and the gentle wisdom they carry.', 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&h=600&fit=crop', 'image', 'Culture', 1, '2025-02-25', 178, 'author-user-peter-kiplangat', datetime('now'), datetime('now'));