-- Add new columns to Book table
ALTER TABLE Book ADD COLUMN rentalPrice REAL;
ALTER TABLE Book ADD COLUMN isFeatured INTEGER DEFAULT 0;
ALTER TABLE Book ADD COLUMN featuredOrder INTEGER;
ALTER TABLE Book ADD COLUMN rating REAL DEFAULT 0;
ALTER TABLE Book ADD COLUMN reviewCount INTEGER DEFAULT 0;
